###
// RENDER
GET https://cse341-96fi.onrender.com/contacts HTTP/1.1

###
// RENDER Ryker
GET https://cse341-96fi.onrender.com/contacts/650f6674db07b6b4b74cc340 HTTP/1.1

###
// RENDER Corinne
GET https://cse341-96fi.onrender.com/contacts/650f6674db07b6b4b74cc341 HTTP/1.1

###
// LOCALHOST Kassidy
GET https://cse341-96fi.onrender.com/contacts/650f6674db07b6b4b74cc342 HTTP/1.1